stages:
    - test    
    - deploy

include:
  - project: 'infra/shared_ci'
    file: '/omnipublish-v6.yml'

# Environment variables are defined in GitLab CI/CD settings at projet level:
# NEXUS_URL is the private registry URL
# NEXUS_AUTH is the base64 encoded credentials on Nexus registry.
eslint:
    stage: test
    image: node:14-alpine
    before_script:
        - npm config set _auth $NEXUS_AUTH
        - npm install
    script:
        - npm run lint
tscheck:
    stage: test
    image: node:14-alpine
    before_script:
        - npm config set _auth $NEXUS_AUTH
        - npm install
    script:
        - npm run tscheck
unitTests:
    stage: test
    image: node:14-alpine
    before_script:
        - npm config set _auth $NEXUS_AUTH
        - npm install
    script:
        - npm run test
