stages:
    - test

# Environment variables are defined in GitLab CI/CD settings at projet level:
# NEXUS_URL is the private registry URL
# NEXUS_AUTH is the base64 encoded credentials on Nexus registry.
tslint:
    stage: test
    image: node:alpine
    before_script:
        - npm config set _auth $NEXUS_AUTH
        - npm install
    script:
        - npm run lint:test
tscheck:
    stage: test
    image: node:alpine
    before_script:
        - npm config set _auth $NEXUS_AUTH
        - npm install
    script:
        - npm run tscheck
unitTests:
    stage: test
    image: node:alpine
    before_script:
        - npm config set _auth $NEXUS_AUTH
        - npm install
    script:
        - npm run test
