##### Common settings #####
.common-cache-settings: &common-cache-settings
    key: ${CI_COMMIT_REF_SLUG}
    untracked: true
    paths:
        - .yarn
        - node_modules/
        - 'apps/*/node_modules/'
        - 'libs/*/node_modules/'

.node-image: &node-image node:14-alpine

.before-script-common: &before-script-common
    before_script:
        - yarn install
############################
image: *node-image

stages:
    - prepare
    - test
    # - deploy

# include:
#   - project: 'infra/shared_ci'
#     file: '/omnipublish-v6.yml'

# This will apply to all jobs except installDeps, which its own cache settings
cache:
    <<: *common-cache-settings
    policy: pull

installDeps:
    stage: prepare
    script:
        - yarn install
    cache:
        <<: *common-cache-settings
        policy: pull-push

lint:
    stage: test
    <<: *before-script-common
    script:
        - yarn lint

tscheck:
    stage: test
    <<: *before-script-common
    script:
        - yarn tscheck

unitTests:
    stage: test
    <<: *before-script-common
    variables:
        SKIP_PREFLIGHT_CHECK: 'true'
    script:
        - yarn test

e2eApi:
    stage: test
    services:
        - arangodb:3.7
        - rabbitmq:3-management-alpine
    variables:
        NODE_ENV: test
        ARANGO_NO_AUTH: 1
        ARANGO_URL: 'http://root:@arangodb:8529'
        AUTH_KEY: 123456789
        AMQP_HOST: rabbitmq
        AMQP_USERNAME: guest
        AMQP_PASSWORD: guest
    <<: *before-script-common
    script:
        - cd apps/core/
        - yarn run test:e2e:api

# e2eIndexationManager:
#     stage: test
#     image: node:14-alpine
#     services:
#         - arangodb:3.7
#         - rabbitmq:3-management-alpine
#         - name: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
#           alias: elasticsearch
#           command: [ "bin/elasticsearch", "-Expack.security.enabled=false", "-Ediscovery.type=single-node" ]
#     variables:
#         NODE_ENV: test
#         ARANGO_NO_AUTH: 1
#         ARANGO_URL: 'http://root:@arangodb:8529'
#         AUTH_KEY: 123456789
#         AMQP_HOST: rabbitmq
#         AMQP_USERNAME: guest
#         AMQP_PASSWORD: guest
#         ES_JAVA_OPTS: -Xms512m -Xmx512m # For ElasticSearch
#     before_script:
#         - npm config set _auth $NEXUS_AUTH
#         - npm install
#     script:
#         - npm run test:e2e:indexationManager
