version: "3"
services:
  preview:
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /Users/smarzykmathieu/Dev/preview:/app
      - /Users/smarzykmathieu/Data/:/data
    network_mode: host
