version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - /Users/smarzykmathieu/Data/:/data
      - /Users/smarzykmathieu/Demo/:/demo
    network_mode: host
    command: sh -c "./start.sh"
