version: "3"
services:
  preview:
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - /Users/smarzykmathieu/Data/:/data
      - /Users/smarzykmathieu/Demo/:/demo
    network_mode: host
